package com.examle.biometriclogin.utility

object Constants {
    const val PREFERENCE_NAME = "ANDROIDX_BIOMETRIC"
    const val FACE_AVAILABLE = "BIOMETRIC_FACE_AVAILABLE"
    const val TYPE_OF_BIO = "BIOMETRIC_FACE_AVAILABLE"
    const val INIT_BIO_ENCRYPT = "INIT_BIOMETRIC_ENCRYPT_CIPHER"
    const val IS_BIO_ENROLLED = "IS_BIOMETRIC_ENROLLED"
    const val IS_BIO_CHANGED = "IS_BIOMETRIC_CHANGED"
    const val KEY_NAME = "ANDROID_X_BIO"
    const val FINGERPRINT_AVAILABLE = "BIOMETRIC_FINGERPRINT_AVAILABLE"
}